name: Build and Deploy GitBook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Install GitBook CLI
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.3

      - name: Clean unsupported GitBook tags
        run: |
          find . -name "*.md" -type f -print0 | xargs -0 sed -i -E 's/\{\% hint.*\%\}/> **Note:** /g'
          find . -name "*.md" -type f -print0 | xargs -0 sed -i -E 's/\{\% endhint.*\%\}//g'

      - name: Create book.json
        run: |
          cat > book.json <<'EOF'
{
  "plugins": ["-highlight", "fontsettings", "theme-default"],
  "styles": {
    "website": "styles/website.css"
  }
}
EOF

      - name: Add global CSS
        run: |
          mkdir -p styles
          cat > styles/website.css <<'EOF'
@import url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css');
.markdown-section h1:before,.markdown-section h2:before,.markdown-section h3:before {
  font-family:"Font Awesome 6 Free"; font-weight:900; margin-right:8px;}
#book-summary .summary a i,.book-summary .summary a i,.summary a i,.nav a i {
  font-family:"Font Awesome 6 Free"; font-weight:900; margin-right:8px; display:inline-block; vertical-align:middle;}
.embed-placeholder {
  width:100%; min-height:180px; display:flex; align-items:center; justify-content:center;
  background:#111; color:#fff; border-radius:6px; margin:8px 0;
}
.embed-placeholder::after { content:"Video will load..."; opacity:0.75; }
EOF

      - name: Install GitBook plugins
        run: gitbook install

      - name: Build GitBook
        run: |
          gitbook build
          # Inject FontAwesome CDN fallback in HTML
          find _book -name "*.html" -type f -exec sed -i \
            's#</head>#<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer"/></head>#' {} \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
