name: Build and Deploy GitBook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Install GitBook CLI
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.3

      - name: Clean unsupported GitBook tags
        run: |
          find . -name "*.md" -type f -print0 | xargs -0 sed -i -E 's/\{\% hint.*\%\}/> **Note:** /g'
          find . -name "*.md" -type f -print0 | xargs -0 sed -i -E 's/\{\% endhint.*\%\}//g'

      - name: Create book.json
        run: |
          cat > book.json <<'EOF'
          {
            "plugins": ["-highlight", "fontsettings", "theme-default", "insert-html"],
            "pluginsConfig": {
              "insert-html": {
                "body:end": "<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css' crossorigin='anonymous' referrerpolicy='no-referrer'/>"
              }
            }
          }
          EOF

      - name: Install GitBook plugins
        run: gitbook install

      - name: Build GitBook
        run: gitbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
